INSERT INTO "Customers"("CompanyCode", "CompanyName","ContactName", "ContactTitle", "LocationId") VALUES
('ALFKI','Alfreds Futterkiste','Maria Anders','Sales Representative', 30),
('ANATR','Ana Trujillo Emparedados y helados','Ana Trujillo','Owner', 31),
('ANTON','Antonio Moreno Taquería','Antonio Moreno','Owner', 32),
('AROUT','Around the Horn','Thomas Hardy','Sales Representative', 33),
('BERGS','Berglunds snabbköp','Christina Berglund','Order Administrator', 34),
('BLAUS','Blauer See Delikatessen','Hanna Moos','Sales Representative', 35),
('BLONP','Blondesddsl père et fils','Frédérique Citeaux','Marketing Manager', 36),
('BOLId','BólIdo ComIdas preparadas','Martín Sommer','Owner', 37),
('BONAP','Bon app''','Laurence Lebihan','Owner', 38),
('BOTTM','Bottom-Dollar Markets','Elizabeth Lincoln','Accounting Manager', 39),
('BSBEV','B''s Beverages','Victoria Ashworth','Sales Representative', 40),
('CACTU','Cactus ComIdas para llevar','Patricio Simpson','Sales Agent', 41),
('CENTC','Centro comercial Moctezuma','Francisco Chang','Marketing Manager', 42),
('CHOPS','Chop-suey Chinese','Yang Wang','Owner', 43),
('COMMI','Comércio Mineiro','Pedro Afonso','Sales Associate', 44),
('CONSH','ConsolIdated Holdings','Elizabeth Brown','Sales Representative', 45),
('DRACD','Drachenblut Delikatessen','Sven Ottlieb','Order Administrator', 46),
('DUMON','Du monde entier','Janine Labrune','Owner', 47),
('EASTC','Eastern Connection','Ann Devon','Sales Agent', 48),
('ERNSH','Ernst Handel','Roland Mendel','Sales Manager', 49),
('FAMIA','Familia Arquibaldo','Aria Cruz','Marketing Assistant', 50),
('FISSA','FISSA Fabrica Inter. Salchichas S.A.','Diego Roel','Accounting Manager', 51),
('FOLIG','Folies gourmandes','Martine Rancé','Assistant Sales Agent', 52),
('FOLKO','Folk och fä HB','Maria Larsson','Owner', 53),
('FRANK','Frankenversand','Peter Franken','Marketing Manager', 54),
('FRANR','France restauration','Carine Schmitt','Marketing Manager', 55),
('FRANS','Franchi S.p.A.','Paolo Accorti','Sales Representative', 56),
('FURIB','Furia Bacalhau e Frutos do Mar','Lino Rodriguez','Sales Manager', 57),
('GALED','Galería del gastrónomo','Eduardo Saavedra','Marketing Manager', 58),
('GODOS','Godos Cocina Típica','José Pedro Freyre','Sales Manager', 59),
('GOURL','Gourmet Lanchonetes','André Fonseca','Sales Associate', 60),
('GREAL','Great Lakes Food Market','Howard Snyder','Marketing Manager', 61),
('GROSR','GROSELLA-Restaurante','Manuel Pereira','Owner', 62),
('HANAR','Hanari Carnes','Mario Pontes','Accounting Manager', 63),
('HILAA','HILARION-Abastos','Carlos Hernández','Sales Representative', 64),
('HUNGC','Hungry Coyote Import Store','Yoshi Latimer','Sales Representative', 65),
('HUNGO','Hungry Owl All-Night Grocers','Patricia McKenna','Sales Associate', 66),
('ISLAT','Island Trading','Helen Bennett','Marketing Manager', 67),
('KOENE','Königlich Essen','Philip Cramer','Sales Associate', 68),
('LACOR','La corne d''abondance','Daniel Tonini','Sales Representative', 69),
('LAMAI','La maison d''Asie','Annette Roulet','Sales Manager', 70),
('LAUGB','Laughing Bacchus Wine Cellars','Yoshi Tannamuri','Marketing Assistant', 71),
('LAZYK','Lazy K Kountry Store','John Steel','Marketing Manager', 72),
('LEHMS','Lehmanns Marktstand','Renate Messner','Sales Representative', 73),
('LETSS','Let''s Stop N Shop','Jaime Yorres','Owner', 74),
('LILAS','LILA-Supermercado','Carlos González','Accounting Manager', 75),
('LINOD','LINO-Delicateses','Felipe Izquierdo','Owner', 76),
('LONEP','Lonesome Pine Restaurant','Fran Wilson','Sales Manager', 77),
('MAGAA','Magazzini Alimentari Riuniti','Giovanni Rovelli','Marketing Manager', 78),
('MAISD','Maison Dewey','Catherine Dewey','Sales Agent', 79),
('MEREP','Mère Paillarde','Jean Fresnière','Marketing Assistant', 80),
('MORGK','Morgenstern Gesundkost','Alexander Feuer','Marketing Assistant', 81),
('NORTS','North/South','Simon Crowther','Sales Associate', 82),
('OCEAN','Océano Atlántico Ltda.','Yvonne Moncada','Sales Agent', 83),
('OLDWO','Old World Delicatessen','Rene Phillips','Sales Representative', 84),
('OTTIK','Ottilies Käseladen','Henriette Pfalzheim','Owner', 85),
('PARIS','Paris spécialités','Marie Bertrand','Owner', 86),
('PERIC','Pericles ComIdas clásicas','Guillermo Fernández','Sales Representative', 87),
('PICCO','Piccolo und mehr','Georg Pipps','Sales Manager', 88),
('PRINI','Princesa Isabel Vinhos','Isabel de Castro','Sales Representative', 89),
('QUEDE','Que Delícia','Bernardo Batista','Accounting Manager', 90),
('QUEEN','Queen Cozinha','Lúcia Carvalho','Marketing Assistant', 91),
('QUICK','QUICK-Stop','Horst Kloss','Accounting Manager', 92),
('RANCH','Rancho grande','Sergio Gutiérrez','Sales Representative', 93),
('RATTC','Rattlesnake Canyon Grocery','Paula Wilson','Assistant Sales Representative', 94),
('REGGC','Reggiani Caseifici','Maurizio Moroni','Sales Associate', 95),
('RICAR','Ricardo Adocicados','Janete Limeira','Assistant Sales Agent', 96),
('RICSU','Richter Supermarkt','Michael Holz','Sales Manager', 97),
('ROMEY','Romero y tomillo','Alejandra Camino','Accounting Manager', 98),
('SANTG','Santé Gourmet','Jonas Bergulfsen','Owner', 99),
('SAVEA','Save-a-lot Markets','Jose Pavarotti','Sales Representative', 100),
('SEVES','Seven Seas Imports','Hari Kumar','Sales Manager', 101),
('SIMOB','Simons bistro','Jytte Petersen','Owner', 102),
('SPECD','Spécialités du monde','Dominique Perrier','Marketing Manager', 103),
('SPLIR','Split Rail Beer & Ale','Art Braunschweiger','Sales Manager', 104),
('SUPRD','Suprêmes délices','Pascale Cartrain','Accounting Manager', 105),
('THEBI','The Big Cheese','Liz Nixon','Marketing Manager', 106),
('THECR','The Cracker Box','Liu Wong','Marketing Assistant', 107),
('TOMSP','Toms Spezialitäten','Karin Josephs','Marketing Manager', 108),
('TORTU','Tortuga Restaurante','Miguel Angel Paolino','Owner', 109),
('TRADH','Tradição Hipermercados','Anabela Domingues','Sales Representative', 110),
('TRAIH','Trail''s Head Gourmet Provisioners','Helvetius Nagy','Sales Associate', 111),
('VAFFE','Vaffeljernet','Palle Ibsen','Sales Manager', 112),
('VICTE','Victuailles en stock','Mary Saveley','Sales Agent', 113),
('VINET','Vins et alcools Chevalier','Paul Henriot','Accounting Manager', 114),
('WANDK','Die Wandernde Kuh','Rita Müller','Sales Representative', 115),
('WARTH','Wartian Herkku','Pirkko Koskitalo','Accounting Manager', 116),
('WELLI','Wellington Importadora','Paula Parente','Sales Manager', 117),
('WHITC','White Clover Markets','Karl Jablonski','Owner', 118),
('WILMK','Wilman Kala','Matti Karttunen','Owner/Marketing Assistant', 119),
('WOLZA','Wolski  Zajazd','Zbyszek Piestrzeniewicz','Owner', 120);