INSERT INTO "Suppliers" ("CompanyName", "ContactName", "ContactTitle", "HomePage", "LocationId") VALUES
('Exotic LiquIds','Charlotte Cooper','Purchasing Manager',NULL,1),
('New Orleans Cajun Delights','Shelley Burke','Order Administrator','#CAJUN.HTM#',2),
('Grandma Kelly''s Homestead','Regina Murphy','Sales Representative',NULL,3),
('Tokyo Traders','Yoshi Nagase','Marketing Manager',NULL,4),
('Cooperativa de Quesos ''Las Cabras''','Antonio del Valle Saavedra','Export Administrator',NULL,5),
('Mayumi''s','Mayumi Ohno','Marketing Representative','Mayumi''s (on the World WIde Web)#http://www.microsoft.com/accessdev/sampleapps/mayumi.htm#',6),
('Pavlova, Ltd.','Ian Devling','Marketing Manager',NULL,7),
('Specialty Biscuits, Ltd.','Peter Wilson','Sales Representative',NULL,8),
('PB Knäckebröd AB','Lars Peterson','Sales Agent',NULL,9),
('Refrescos Americanas LTDA','Carlos Diaz','Marketing Manager',NULL,10),
('Heli Süßwaren GmbH & Co. KG','Petra Winkler','Sales Manager',NULL,11),
('Plutzer Lebensmittelgroßmärkte AG','Martin Bein','International Marketing Mgr.','Plutzer (on the World WIde Web)#http://www.microsoft.com/accessdev/sampleapps/plutzer.htm#',12),
('Nord-Ost-Fisch Handelsgesellschaft mbH','Sven Petersen','Coordinator Foreign Markets',NULL,13),
('Formaggi Fortini s.r.l.','Elio Rossi','Sales Representative','#FORMAGGI.HTM#',14),
('Norske Meierier','Beate VileId','Marketing Manager',NULL,15),
('Bigfoot Breweries','Cheryl Saylor','Regional Account Rep.',NULL,16),
('Svensk Sjöföda AB','Michael Björn','Sales Representative',NULL,17),
('Aux joyeux ecclésiastiques','Guylène Nodier','Sales Manager',NULL,18),
('New England Seafood Cannery','Robb Merchant','Wholesale Account Agent',NULL,19),
('Leka Trading','Chandra Leka','Owner',NULL,20),
('Lyngbysild','Niels Petersen','Sales Manager',NULL,21),
('Zaanse Snoepfabriek','Dirk Luchte','Accounting Manager',NULL,22),
('Karkki Oy','Anne Heikkonen','Product Manager',NULL,23),
('G''day, Mate','Wendy Mackenzie','Sales Representative','G''day Mate (on the World WIde Web)#http://www.microsoft.com/accessdev/sampleapps/gdaymate.htm#',24),
('Ma Maison','Jean-Guy Lauzon','Marketing Manager',NULL,25),
('Pasta Buttini s.r.l.','Giovanni Giudici','Order Administrator',NULL,26),
('Escargots Nouveaux','Marie Delamare','Sales Manager',NULL,27),
('Gai pâturage','Eliane Noz','Sales Representative',NULL,28),
('Forêts d''érables','Chantal Goulet','Accounting Manager',NULL,29);
