CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);


DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200713021021_Initial') THEN
    CREATE TABLE "Categories" (
        "CategoryId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "CategoryName" text NOT NULL,
        "Description" text NULL,
        CONSTRAINT "PK_Categories" PRIMARY KEY ("CategoryId")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200713021021_Initial') THEN
    CREATE TABLE "Customers" (
        "CustomerId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "CompanyCode" text NULL,
        "CompanyName" text NOT NULL,
        "ContactName" text NULL,
        "ContactTitle" text NULL,
        "Address" text NULL,
        "City" text NULL,
        "Region" text NULL,
        "PostalCode" text NULL,
        "Country" text NULL,
        "Phone" text NULL,
        "Fax" text NULL,
        CONSTRAINT "PK_Customers" PRIMARY KEY ("CustomerId")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200713021021_Initial') THEN
    CREATE TABLE "Employees" (
        "EmployeeId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "LastName" text NOT NULL,
        "FirstName" text NOT NULL,
        "Title" text NULL,
        "TitleOfCourtesy" text NULL,
        "BirthDate" timestamp without time zone NOT NULL,
        "HireDate" timestamp without time zone NOT NULL,
        "Notes" text NULL,
        "ReportsTo" integer NULL,
        "Address" text NULL,
        "City" text NULL,
        "Region" text NULL,
        "PostalCode" text NULL,
        "Country" text NULL,
        "HomePhone" text NULL,
        "Extension" text NULL,
        CONSTRAINT "PK_Employees" PRIMARY KEY ("EmployeeId")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200713021021_Initial') THEN
    CREATE TABLE "Shippers" (
        "ShipperId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "CompanyName" text NOT NULL,
        "Phone" text NULL,
        CONSTRAINT "PK_Shippers" PRIMARY KEY ("ShipperId")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200713021021_Initial') THEN
    CREATE TABLE "Suppliers" (
        "SupplierId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "CompanyName" text NOT NULL,
        "ContactName" text NULL,
        "ContactTitle" text NULL,
        "HomePage" text NULL,
        "Address" text NULL,
        "City" text NULL,
        "Region" text NULL,
        "PostalCode" text NULL,
        "Country" text NULL,
        "Phone" text NULL,
        "Fax" text NULL,
        CONSTRAINT "PK_Suppliers" PRIMARY KEY ("SupplierId")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200713021021_Initial') THEN
    CREATE TABLE "Orders" (
        "OrderId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "CustomerId" integer NOT NULL,
        "EmployeeId" integer NOT NULL,
        "OrderDate" timestamp without time zone NOT NULL,
        "RequiredDate" timestamp without time zone NOT NULL,
        "ShippedDate" timestamp without time zone NULL,
        "ShipVia" integer NOT NULL,
        "Freight" numeric NOT NULL,
        "ShipName" text NULL,
        "ShipAddress" text NULL,
        "ShipCity" text NULL,
        "ShipRegion" text NULL,
        "ShipPostalCode" text NULL,
        "ShipCountry" text NULL,
        CONSTRAINT "PK_Orders" PRIMARY KEY ("OrderId"),
        CONSTRAINT "FK_Orders_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("CustomerId") ON DELETE CASCADE,
        CONSTRAINT "FK_Orders_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("EmployeeId") ON DELETE CASCADE,
        CONSTRAINT "FK_Orders_Shippers_ShipVia" FOREIGN KEY ("ShipVia") REFERENCES "Shippers" ("ShipperId") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200713021021_Initial') THEN
    CREATE TABLE "Products" (
        "ProductId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "CategoryId" integer NULL,
        "ProductName" text NOT NULL,
        "SupplierId" integer NULL,
        "QuantityPerUnit" text NULL,
        "UnitPrice" numeric NOT NULL,
        "UnitsInStock" integer NOT NULL,
        "UnitsOnOrder" integer NOT NULL,
        "ReorderLevel" integer NOT NULL,
        "Discontinued" integer NOT NULL,
        CONSTRAINT "PK_Products" PRIMARY KEY ("ProductId"),
        CONSTRAINT "FK_Products_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("CategoryId") ON DELETE RESTRICT,
        CONSTRAINT "FK_Products_Suppliers_SupplierId" FOREIGN KEY ("SupplierId") REFERENCES "Suppliers" ("SupplierId") ON DELETE RESTRICT
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200713021021_Initial') THEN
    CREATE TABLE "Order Details" (
        "OrderId" integer NOT NULL,
        "ProductId" integer NOT NULL,
        "UnitPrice" numeric NOT NULL,
        "Quantity" integer NOT NULL,
        "Discount" numeric NOT NULL,
        CONSTRAINT "PK_Order Details" PRIMARY KEY ("OrderId", "ProductId"),
        CONSTRAINT "FK_Order Details_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("OrderId") ON DELETE CASCADE,
        CONSTRAINT "FK_Order Details_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("ProductId") ON DELETE CASCADE
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200713021021_Initial') THEN
    CREATE INDEX "FullName" ON "Employees" ("FirstName", "LastName");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200713021021_Initial') THEN
    CREATE INDEX "IX_Order Details_ProductId" ON "Order Details" ("ProductId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200713021021_Initial') THEN
    CREATE INDEX "IX_Orders_CustomerId" ON "Orders" ("CustomerId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200713021021_Initial') THEN
    CREATE INDEX "IX_Orders_EmployeeId" ON "Orders" ("EmployeeId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200713021021_Initial') THEN
    CREATE INDEX "IX_Orders_ShipVia" ON "Orders" ("ShipVia");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200713021021_Initial') THEN
    CREATE INDEX "IX_Products_CategoryId" ON "Products" ("CategoryId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200713021021_Initial') THEN
    CREATE INDEX "IX_Products_SupplierId" ON "Products" ("SupplierId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200713021021_Initial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20200713021021_Initial', '3.1.6');
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200713223542_Locations') THEN
    ALTER TABLE "Suppliers" DROP COLUMN "Address";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200713223542_Locations') THEN
    ALTER TABLE "Suppliers" DROP COLUMN "City";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200713223542_Locations') THEN
    ALTER TABLE "Suppliers" DROP COLUMN "Country";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200713223542_Locations') THEN
    ALTER TABLE "Suppliers" DROP COLUMN "Fax";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200713223542_Locations') THEN
    ALTER TABLE "Suppliers" DROP COLUMN "Phone";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200713223542_Locations') THEN
    ALTER TABLE "Suppliers" DROP COLUMN "PostalCode";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200713223542_Locations') THEN
    ALTER TABLE "Suppliers" DROP COLUMN "Region";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200713223542_Locations') THEN
    ALTER TABLE "Suppliers" ADD "LocationId" integer NOT NULL DEFAULT 0;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200713223542_Locations') THEN
    CREATE TABLE "Locations" (
        "LocationId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "Address" text NULL,
        "City" text NULL,
        "Region" text NULL,
        "PostalCode" text NULL,
        "Country" text NULL,
        "Phone" text NULL,
        "Extension" text NULL,
        "Fax" text NULL,
        CONSTRAINT "PK_Locations" PRIMARY KEY ("LocationId")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200713223542_Locations') THEN
    CREATE UNIQUE INDEX "IX_Suppliers_LocationId" ON "Suppliers" ("LocationId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200713223542_Locations') THEN
    CREATE UNIQUE INDEX "IX_Locations_Address" ON "Locations" ("Address");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200713223542_Locations') THEN
    ALTER TABLE "Suppliers" ADD CONSTRAINT "FK_Suppliers_Locations_LocationId" FOREIGN KEY ("LocationId") REFERENCES "Locations" ("LocationId") ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200713223542_Locations') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20200713223542_Locations', '3.1.6');
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200803174508_Customer_Location') THEN
    ALTER TABLE "Customers" DROP COLUMN "Address";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200803174508_Customer_Location') THEN
    ALTER TABLE "Customers" DROP COLUMN "City";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200803174508_Customer_Location') THEN
    ALTER TABLE "Customers" DROP COLUMN "Country";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200803174508_Customer_Location') THEN
    ALTER TABLE "Customers" DROP COLUMN "Fax";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200803174508_Customer_Location') THEN
    ALTER TABLE "Customers" DROP COLUMN "Phone";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200803174508_Customer_Location') THEN
    ALTER TABLE "Customers" DROP COLUMN "PostalCode";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200803174508_Customer_Location') THEN
    ALTER TABLE "Customers" DROP COLUMN "Region";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200803174508_Customer_Location') THEN
    ALTER TABLE "Customers" ADD "LocationId" integer NOT NULL DEFAULT 0;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200803174508_Customer_Location') THEN
    CREATE INDEX "IX_Customers_LocationId" ON "Customers" ("LocationId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200803174508_Customer_Location') THEN
    ALTER TABLE "Customers" ADD CONSTRAINT "FK_Customers_Locations_LocationId" FOREIGN KEY ("LocationId") REFERENCES "Locations" ("LocationId") ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200803174508_Customer_Location') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20200803174508_Customer_Location', '3.1.6');
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200816195710_Order_Location') THEN
    ALTER TABLE "Orders" DROP CONSTRAINT "FK_Orders_Employees_EmployeeId";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200816195710_Order_Location') THEN
    ALTER TABLE "Orders" DROP CONSTRAINT "FK_Orders_Shippers_ShipVia";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200816195710_Order_Location') THEN
    ALTER TABLE "Orders" DROP COLUMN "Freight";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200816195710_Order_Location') THEN
    ALTER TABLE "Orders" DROP COLUMN "ShipAddress";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200816195710_Order_Location') THEN
    ALTER TABLE "Orders" DROP COLUMN "ShipCity";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200816195710_Order_Location') THEN
    ALTER TABLE "Orders" DROP COLUMN "ShipCountry";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200816195710_Order_Location') THEN
    ALTER TABLE "Orders" DROP COLUMN "ShipPostalCode";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200816195710_Order_Location') THEN
    ALTER TABLE "Orders" DROP COLUMN "ShipRegion";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200816195710_Order_Location') THEN
    ALTER TABLE "Orders" ALTER COLUMN "ShipVia" TYPE integer;
    ALTER TABLE "Orders" ALTER COLUMN "ShipVia" DROP NOT NULL;
    ALTER TABLE "Orders" ALTER COLUMN "ShipVia" DROP DEFAULT;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200816195710_Order_Location') THEN
    ALTER TABLE "Orders" ALTER COLUMN "ShippedDate" TYPE timestamp with time zone;
    ALTER TABLE "Orders" ALTER COLUMN "ShippedDate" DROP NOT NULL;
    ALTER TABLE "Orders" ALTER COLUMN "ShippedDate" DROP DEFAULT;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200816195710_Order_Location') THEN
    ALTER TABLE "Orders" ALTER COLUMN "RequiredDate" TYPE timestamp with time zone;
    ALTER TABLE "Orders" ALTER COLUMN "RequiredDate" SET NOT NULL;
    ALTER TABLE "Orders" ALTER COLUMN "RequiredDate" DROP DEFAULT;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200816195710_Order_Location') THEN
    ALTER TABLE "Orders" ALTER COLUMN "OrderDate" TYPE timestamp with time zone;
    ALTER TABLE "Orders" ALTER COLUMN "OrderDate" SET NOT NULL;
    ALTER TABLE "Orders" ALTER COLUMN "OrderDate" DROP DEFAULT;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200816195710_Order_Location') THEN
    ALTER TABLE "Orders" ALTER COLUMN "EmployeeId" TYPE integer;
    ALTER TABLE "Orders" ALTER COLUMN "EmployeeId" DROP NOT NULL;
    ALTER TABLE "Orders" ALTER COLUMN "EmployeeId" DROP DEFAULT;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200816195710_Order_Location') THEN
    ALTER TABLE "Orders" ADD "LocationId" integer NOT NULL DEFAULT 0;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200816195710_Order_Location') THEN
    ALTER TABLE "Orders" ADD "Total" numeric NOT NULL DEFAULT 0.0;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200816195710_Order_Location') THEN
    CREATE INDEX "IX_Orders_LocationId" ON "Orders" ("LocationId");
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200816195710_Order_Location') THEN
    ALTER TABLE "Orders" ADD CONSTRAINT "FK_Orders_Employees_EmployeeId" FOREIGN KEY ("EmployeeId") REFERENCES "Employees" ("EmployeeId") ON DELETE RESTRICT;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200816195710_Order_Location') THEN
    ALTER TABLE "Orders" ADD CONSTRAINT "FK_Orders_Locations_LocationId" FOREIGN KEY ("LocationId") REFERENCES "Locations" ("LocationId") ON DELETE CASCADE;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200816195710_Order_Location') THEN
    ALTER TABLE "Orders" ADD CONSTRAINT "FK_Orders_Shippers_ShipVia" FOREIGN KEY ("ShipVia") REFERENCES "Shippers" ("ShipperId") ON DELETE RESTRICT;
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200816195710_Order_Location') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20200816195710_Order_Location', '3.1.6');
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200918145202_User') THEN
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200918145202_User') THEN
    CREATE TABLE "Users" (
        "UserId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "UserIdentifier" uuid NOT NULL DEFAULT (uuid_generate_v4()),
        "UserName" text NULL,
        "PasswordSalt" bytea NULL,
        "PasswordHash" bytea NULL,
        "AccessToken" text NULL,
        "Value" text NULL,
        "ExpiryDate" timestamp with time zone NULL,
        "CreateDate" timestamp with time zone NULL,
        "RevokeDate" timestamp with time zone NULL,
        CONSTRAINT "PK_Users" PRIMARY KEY ("UserId")
    );
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200918145202_User') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20200918145202_User', '3.1.6');
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200918152807_User_Role') THEN
    ALTER TABLE "Users" ADD "Role" text NOT NULL DEFAULT '';
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20200918152807_User_Role') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20200918152807_User_Role', '3.1.6');
    END IF;
END $$;
